/* ── SPILL DATA ──
** To add a post: copy an existing object in SPILL_POSTS, change the fields, save and push to GitHub.
** To add a bean: copy an object in SPILL_BEANS, update the fields, save and push.
** To add gear: copy an object in SPILL_GEAR, update the fields, save and push.
*/

window.SPILL_POSTS = [
  {
    "slug": "flat-white-fix",
    "title": "Why your flat white tastes like sadness (and how to fix it)",
    "category": "brew",
    "excerpt": "You bought decent beans. Your machine cost more than your first car. And yet. Here's the actual reason your espresso is sour, bitter, or just deeply uninspiring.",
    "date": "March 10, 2026",
    "readTime": "5 min read",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800&q=80",
    "content": "Let's start with the uncomfortable truth: most home espresso is bad. Not because the equipment is bad \u2014 because nobody told you about the three variables that actually matter.\n\n**Grind size is everything**\n\nSour espresso = grind finer. Bitter espresso = grind coarser. That's 90% of troubleshooting right there.\n\n**Your water is probably ruining it**\n\nChlorinated tap water actively fights your coffee's flavour compounds. A Brita jug is the cheapest upgrade you'll ever make.\n\n**Preheat everything**\n\nA cold portafilter and cup drop your shot temperature by 5-10\u00b0C. Run hot water through the portafilter before every shot. Fill your cup with hot water while the shot pulls. Empty it before pouring. This alone will transform your flat white."
  },
  {
    "slug": "pour-over-beginner",
    "title": "The beginner's guide to not ruining pour over",
    "category": "brew",
    "excerpt": "Everything you need to pull off a V60 without crying into the sink at 7am. Starting from absolute zero.",
    "date": "Feb 20, 2026",
    "readTime": "6 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    "content": "Pour over looks intimidating. It's actually very simple.\n\n**The recipe**\n\n18g coffee, 300g water at 92\u00b0C. Total brew time 3-3.5 minutes.\n\n**The method**\n\n1. Rinse filter with hot water. 2. Add grounds, make a small well. 3. Pour 40g water for bloom, wait 30 seconds. 4. Pour in slow circles to 150g. 5. Continue to 300g. 6. Let drain.\n\nToo slow? Grind coarser. Too fast? Grind finer."
  },
  {
    "slug": "aeropress-inverted",
    "title": "The inverted Aeropress method: why it works better",
    "category": "brew",
    "excerpt": "The standard method is fine. The inverted method is better. Here's the difference and when to use each.",
    "date": "Feb 15, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800&q=80",
    "content": "The inverted method gives you more control over steep time and stops coffee dripping through before you're ready.\n\n**The recipe**\n\n15g medium-fine ground coffee, 200ml at 90\u00b0C, stir, 2 minute steep, flip and press over 30 seconds.\n\n**Standard vs inverted**\n\nStandard: faster, cleaner. Inverted: more body, more control, better results."
  },
  {
    "slug": "french-press-mistakes",
    "title": "5 French press mistakes you're definitely making",
    "category": "brew",
    "excerpt": "The French press is the most forgiving brewer in the world. And yet people still manage to make it taste like a bin.",
    "date": "Feb 10, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    "content": "**Mistake 1: Boiling water**\n\nUse 94\u00b0C, not boiling. Boiling scorches the grounds.\n\n**Mistake 2: Too fine a grind**\n\nFrench press needs coarse grind. Fine = muddy and bitter.\n\n**Mistake 3: Not timing the steep**\n\n4 minutes. Set a timer. Every time.\n\n**Mistake 4: Pressing too hard**\n\nGentle pressure. Forcing agitates grounds and makes it bitter.\n\n**Mistake 5: Leaving it in the press**\n\nDecant immediately or it keeps extracting."
  },
  {
    "slug": "moka-pot-guide",
    "title": "How to use a Moka pot without burning everything",
    "category": "brew",
    "excerpt": "The Moka pot has a reputation for bitter, scalded coffee. That's because almost everyone uses it wrong.",
    "date": "Feb 5, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&q=80",
    "content": "**The secret: low heat**\n\nLow-medium heat, lid open, watch until the flow slows from a steady stream to a spit. Remove immediately.\n\n**The grind**\n\nMedium \u2014 between espresso and filter. Not fine espresso grind or it'll clog.\n\n**Don't tamp**\n\nJust level the grounds. Tamping creates too much resistance."
  },
  {
    "slug": "chemex-guide",
    "title": "Chemex: the most beautiful way to make coffee",
    "category": "brew",
    "excerpt": "It looks like a lab instrument and brews like a dream. The Chemex guide.",
    "date": "Jan 30, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1522125670776-3c7abb882bc2?w=800&q=80",
    "content": "The Chemex uses a thicker filter than a V60, producing a cleaner, brighter cup with less body.\n\n**Recipe for 500ml**\n\n30g coffee (medium grind), 500g water at 94\u00b0C.\n\n**Method**\n\nRinse the filter thoroughly \u2014 it adds papery taste if you skip this. Bloom 60g for 45 seconds. Pour slowly to 500g. Drain time: 4-5 minutes."
  },
  {
    "slug": "cold-brew-concentrate",
    "title": "Cold brew concentrate: make it once, thank yourself all week",
    "category": "brew",
    "excerpt": "12-hour steep, zero heat, maximum vibes. The most low-effort coffee upgrade you can make.",
    "date": "Jan 25, 2026",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80",
    "content": "**The ratio**\n\n1:6 coffee to water (100g coffee to 600ml water). Coarse grind.\n\n**The method**\n\nCombine in a large jar, stir, refrigerate 12-16 hours, strain through fine mesh.\n\n**How to serve**\n\nDilute 1:1 with water or milk over ice. This is concentrate \u2014 don't drink it straight."
  },
  {
    "slug": "espresso-ratio-guide",
    "title": "Espresso ratios explained: 1:2, ristretto, lungo",
    "category": "brew",
    "excerpt": "Numbers, ratios, yield weights. Here's what they all mean and which one you should be pulling.",
    "date": "Jan 20, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
    "content": "**Standard espresso: 1:2**\n\n18g in, 36g out. The baseline.\n\n**Ristretto: 1:1.5**\n\n18g in, 27g out. Shorter, sweeter, more concentrated. Best for milk drinks.\n\n**Lungo: 1:3**\n\n18g in, 54g out. More volume, more bitter notes.\n\n**For flat whites**\n\nPull a ristretto. The sweetness cuts through milk beautifully."
  },
  {
    "slug": "milk-steaming-guide",
    "title": "How to steam milk properly without burning it",
    "category": "brew",
    "excerpt": "Silky microfoam is the difference between a flat white and warm frothy sadness.",
    "date": "Dec 28, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&q=80",
    "content": "**Target texture**\n\nMicrofoam: tiny bubbles so small the milk looks glossy, like wet paint.\n\n**Temperature**\n\n60-65\u00b0C. Hot enough to feel uncomfortable to hold but not scalding. Above 70\u00b0C the milk proteins break down.\n\n**Technique**\n\nTip of wand just below surface, slightly off-centre. Create a whirlpool. As it stretches, lower the jug to keep the tip just below surface."
  },
  {
    "slug": "espresso-tonic-recipe",
    "title": "Espresso tonic: the drink that shouldn't work but does",
    "category": "brew",
    "excerpt": "Two shots over tonic water. Sounds wrong. Tastes like a revelation. Here's why it works.",
    "date": "Dec 20, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?w=800&q=80",
    "content": "The bitterness of tonic and espresso cancel each other out. The quinine in the tonic lifts the fruity notes in the coffee.\n\n**Recipe**\n\n120ml quality tonic (Fever-Tree) over ice. Pull a double shot, let cool 30 seconds, pour slowly over the back of a spoon.\n\n**Use a light roast**\n\nThe fruity bright notes work best. Dark roast tastes medicinal in tonic."
  },
  {
    "slug": "latte-art-basics",
    "title": "Latte art for beginners: the heart and the rosette",
    "category": "brew",
    "excerpt": "You don't need a $3000 machine or barista training. Just patience and this guide.",
    "date": "Nov 28, 2025",
    "readTime": "6 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&q=80",
    "content": "**First: nail the microfoam**\n\nYou cannot pour latte art with bad milk. It needs to be glossy and silky.\n\n**The heart**\n\nPour from high to incorporate. When cup is 60% full, lower jug to surface, pour into one spot until milk appears, then cut through.\n\n**The rosette**\n\nSame start, but wiggle the jug side to side while pulling back, then cut through."
  },
  {
    "slug": "4-6-method",
    "title": "The 4:6 method: the pour over technique that won the world championship",
    "category": "brew",
    "excerpt": "Tetsu Kasuya won the 2016 World Brewers Cup with this. Here's how to do it at home.",
    "date": "Aug 20, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    "content": "**The concept**\n\nSplit water into two phases: the first 40% controls sweetness and acidity, the second 60% controls strength.\n\n**The recipe**\n\n20g coffee, 300g water at 93\u00b0C.\n\n0:00 pour 50g, 0:45 pour to 130g, 1:30 pour to 180g, 2:10 pour to 240g, 2:50 pour to 300g."
  },
  {
    "slug": "lungo-vs-americano",
    "title": "Lungo vs Americano: they are not the same thing",
    "category": "brew",
    "excerpt": "Both are espresso with water added. They taste completely different. Here's why.",
    "date": "Oct 15, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?w=800&q=80",
    "content": "**Lungo**\n\nMore water pushed through the puck during extraction. Longer extraction, more bitter.\n\n**Americano**\n\nShort espresso plus hot water added after. Diluted espresso. Cleaner taste.\n\n**Which is better?**\n\nAmericano. Concentrated espresso flavour diluted to a reasonable volume without over-extraction bitterness."
  },
  {
    "slug": "nitro-cold-brew",
    "title": "Nitro cold brew: what it is and how to make it at home",
    "category": "brew",
    "excerpt": "Cold brew infused with nitrogen gas. Creamy, dark, looks like Guinness.",
    "date": "Dec 5, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    "content": "Nitrogen creates much smaller bubbles than CO2, giving nitro cold brew its creamy texture and cascading pour.\n\n**Why it tastes sweeter**\n\nNitrogen suppresses bitter taste receptors slightly.\n\n**Making it at home**\n\nYou need a whipped cream dispenser and N2O cartridges. Make cold brew, put in dispenser, charge with 2 cartridges, refrigerate overnight."
  },
  {
    "slug": "grinding-for-espresso",
    "title": "Dialling in your espresso grind: a practical guide",
    "category": "brew",
    "excerpt": "The most frustrating part of home espresso. Here's the framework that makes it less maddening.",
    "date": "Jan 5, 2026",
    "readTime": "6 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1518057111178-44a106bad636?w=800&q=80",
    "content": "**The target**\n\n18g in, 36g out, 25-30 seconds.\n\n**Too fast (under 20s)**\n\nGrind finer. Tastes sour and thin.\n\n**Too slow (over 35s)**\n\nGrind coarser. Tastes bitter and harsh.\n\n**Rule**\n\nChange one thing at a time. Never adjust dose and grind simultaneously."
  },
  {
    "slug": "coffee-freshness-guide",
    "title": "How fresh is fresh? The complete guide to coffee shelf life",
    "category": "brew",
    "excerpt": "Best before dates are marketing. Roast dates are truth. Here's what the numbers mean.",
    "date": "Jul 15, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80",
    "content": "**Days 1-3 post-roast**\n\nToo fresh. CO2 interferes with extraction.\n\n**Days 4-21**\n\nThe sweet spot. Peak flavour.\n\n**Days 22-42**\n\nDecent but declining.\n\n**Day 42+**\n\nStale. The interesting stuff is gone. Stop buying supermarket coffee."
  },
  {
    "slug": "water-temperature-guide",
    "title": "Water temperature for coffee: the definitive guide",
    "category": "brew",
    "excerpt": "Too hot burns it. Too cold under-extracts it. The actual numbers for every brew method.",
    "date": "Jan 10, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1484980972926-edee96e0960d?w=800&q=80",
    "content": "**Espresso: 90-94\u00b0C**\n\nHigher for lighter roasts. Lower for darker.\n\n**Filter (V60, Chemex, Aeropress): 90-96\u00b0C**\n\nLighter roasts need higher temps.\n\n**French press: 94-96\u00b0C**\n\nCoarser grind needs a bit more heat.\n\n**Cold brew: ambient temperature**\n\nTime replaces heat."
  },
  {
    "slug": "vietnamese-iced-coffee",
    "title": "Vietnamese iced coffee: the sweetest way to start the day",
    "category": "brew",
    "excerpt": "Condensed milk, strong drip coffee, ice. Three ingredients, maximum satisfaction.",
    "date": "Dec 15, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
    "content": "**What you need**\n\nPhin filter (~$10), Vietnamese-style dark roast, sweetened condensed milk.\n\n**Method**\n\n2 tbsp condensed milk in a glass. Brew 25-30g coffee through the Phin directly into the glass. Stir. Pour over ice.\n\n**The coffee**\n\nTraditionally Robusta, which has more caffeine and earthier flavour. Part of the experience."
  },
  {
    "slug": "coffee-and-food-pairing",
    "title": "Coffee and food pairing: what actually works",
    "category": "brew",
    "excerpt": "Chocolate and coffee is obvious. Here are the pairings nobody talks about that are genuinely extraordinary.",
    "date": "Aug 10, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1522125670776-3c7abb882bc2?w=800&q=80",
    "content": "**Ethiopian natural + citrus pastry**\n\nThe blueberry notes amplify next to lemon or orange. Life-changing.\n\n**Colombian + cardamom**\n\nThe caramel sweetness with anything cardamom-spiced.\n\n**Sumatra + dark chocolate**\n\nEarthiness and low acidity cuts through rich dark chocolate perfectly.\n\n**Cold brew + vanilla ice cream**\n\nAffogato. Make it immediately."
  },
  {
    "slug": "decaf-specialty",
    "title": "Decaf doesn't have to be terrible: the specialty decaf revolution",
    "category": "brew",
    "excerpt": "For decades, decaf meant sad flavourless water. Things have changed significantly.",
    "date": "Nov 5, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&q=80",
    "content": "**The old problem**\n\nTraditional decaffeination uses solvents that strip flavour with caffeine.\n\n**Swiss Water Process**\n\nNo chemicals. 99.9% caffeine-free. Much better flavour.\n\n**CO2 Process**\n\nMost flavour-preserving. What specialty roasters use.\n\n**What to buy**\n\nLook for Swiss Water or CO2 processed decaf from specialty roasters."
  },
  {
    "slug": "yirgacheffe-review",
    "title": "Ethiopian Yirgacheffe: the wine drinker's gateway drug",
    "category": "beans",
    "excerpt": "Blueberry, dark chocolate, and a little bit of chaos. Ethiopia's most famous coffee region.",
    "date": "March 8, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
    "content": "If someone tells you coffee can't taste like blueberries, hand them a cup of natural-processed Yirgacheffe and wait.\n\n**What is Yirgacheffe?**\n\nA small town in southern Ethiopia, considered the birthplace of coffee. Altitude 1750-2200m, ancient heirloom varieties.\n\n**Tasting notes**\n\nNatural: blueberry, dark chocolate, wine. Washed: jasmine, bergamot, lemon.\n\n**Best brew method**\n\nFilter. Always filter."
  },
  {
    "slug": "colombia-huila-guide",
    "title": "Colombia Huila: the crowd-pleasing benchmark",
    "category": "beans",
    "excerpt": "Caramel, red apple, balanced acidity. The Colombian coffee that makes everyone happy.",
    "date": "March 2, 2026",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    "content": "Huila is Colombia's most celebrated coffee department. High altitude, volcanic soil, careful processing.\n\n**Tasting notes**\n\nCaramel, red apple, milk chocolate. Medium acidity, medium body.\n\n**Who it's for**\n\nEveryone. Approachable, well-balanced, almost impossible to brew badly."
  },
  {
    "slug": "natural-processing-explained",
    "title": "Natural processing: why these beans taste like fruit",
    "category": "beans",
    "excerpt": "The whole cherry is dried with the fruit intact. The result is extraordinary.",
    "date": "Feb 25, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80",
    "content": "**What happens**\n\nThe whole coffee cherry is dried on raised beds for 3-6 weeks. The fruit ferments slightly as it dries.\n\n**The result**\n\nFruity, wine-like, heavier body. Blueberry, strawberry, tropical fruit.\n\n**The risk**\n\nDone wrong: fermented and defective. Done right: the most exciting coffee you'll ever taste."
  },
  {
    "slug": "kenya-aa-review",
    "title": "Kenya AA: the coffee that makes you think",
    "category": "beans",
    "excerpt": "Bright, complex, challenging. Kenyan coffee is not for everyone. For those it's for, it's everything.",
    "date": "Feb 12, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
    "content": "**What makes Kenya different**\n\nThe SL28 and SL34 varieties produce a distinctive blackcurrant acidity found nowhere else.\n\n**Tasting notes**\n\nBlackcurrant, grapefruit, brown sugar. High acidity, complex.\n\n**Best as filter**\n\nThe brightness and complexity shine in pour over."
  },
  {
    "slug": "sumatra-mandheling",
    "title": "Sumatra Mandheling: the coffee that punches you in the face (affectionately)",
    "category": "beans",
    "excerpt": "Earthy, full-bodied, low acidity. For people who want their coffee to taste like coffee.",
    "date": "Feb 6, 2026",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    "content": "**Wet-hulling (Giling Basah)**\n\nUnique Indonesian process where parchment is removed while the bean still has high moisture. Creates the earthy flavours.\n\n**Tasting notes**\n\nEarth, cedar, dark chocolate, tobacco, very full body.\n\n**Who it's for**\n\nEspresso drinkers. Dark roast fans."
  },
  {
    "slug": "light-roast-vs-dark-roast",
    "title": "Light roast vs dark roast: the real differences",
    "category": "beans",
    "excerpt": "Light roast has more caffeine. Dark roast is stronger. Wait \u2014 that's backwards from what you thought.",
    "date": "Jan 28, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80",
    "content": "**Light roast**\n\nMore caffeine (heat destroys caffeine). More origin flavour. More complex. Harder to brew well.\n\n**Dark roast**\n\nLess caffeine. More roast flavour. More consistent. Easier to brew.\n\n**The myth**\n\nDark roast feels stronger because of bolder flavour, but it's actually lower in caffeine."
  },
  {
    "slug": "geisha-coffee",
    "title": "Gesha coffee: the most expensive beans in the world (and whether they're worth it)",
    "category": "beans",
    "excerpt": "A single origin cup for $100. A bag for $300. We tried it. Here's the verdict.",
    "date": "Jan 22, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
    "content": "**What is Gesha?**\n\nA variety from Ethiopia, grown most famously in Panama. Jasmine, bergamot, peach, honey.\n\n**Is it worth it?**\n\nFor the experience: yes, once. It's genuinely unlike anything else. As a daily drinker: absolutely not. But it's a coffee milestone worth having."
  },
  {
    "slug": "brazil-coffee-guide",
    "title": "Brazilian coffee: why it's the backbone of every espresso blend",
    "category": "beans",
    "excerpt": "Nutty, chocolatey, low acidity. Brazil produces more coffee than any country on earth.",
    "date": "Jan 16, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
    "content": "**Why Brazil is in every blend**\n\nBrazilian naturals provide body, sweetness, and low acidity. They're the base note that makes a blend work.\n\n**As a single origin**\n\nUnderrated. Beautiful hazelnut, dark chocolate, dried fruit. Excellent for espresso."
  },
  {
    "slug": "honey-processing-explained",
    "title": "Honey processing: the middle ground between washed and natural",
    "category": "beans",
    "excerpt": "Some fruit, some clarity. Harder to get right but extraordinary when done well.",
    "date": "Dec 28, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    "content": "**The process**\n\nSkin is removed but some mucilage is left on during drying.\n\n**White/Yellow/Red/Black honey**\n\nRefers to how much mucilage remains. Black honey is almost natural. Yellow is closer to washed.\n\n**The result**\n\nMore body than washed, more clarity than natural."
  },
  {
    "slug": "coffee-variety-guide",
    "title": "Arabica varieties explained: Bourbon, Typica, Caturra and more",
    "category": "beans",
    "excerpt": "The variety of the plant matters as much as the origin. Here's your guide.",
    "date": "Dec 20, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80",
    "content": "**Typica**\n\nThe original Arabica. Low yield, excellent quality.\n\n**Bourbon**\n\nMutation of Typica. Higher yield. Found across Latin America.\n\n**Caturra**\n\nMutation of Bourbon. Compact plant. Common in Colombia.\n\n**Gesha**\n\nEthiopian heirloom. Low yield, extraordinary quality."
  },
  {
    "slug": "robusta-vs-arabica",
    "title": "Robusta vs Arabica: the honest comparison",
    "category": "beans",
    "excerpt": "Robusta has more caffeine, lower quality, and a worse reputation than it deserves.",
    "date": "Dec 14, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
    "content": "**Arabica**\n\nHigher altitude, more complex flavours, lower caffeine, more expensive.\n\n**Robusta**\n\nLower altitude, bolder/harsher, more caffeine, cheaper.\n\n**Where Robusta belongs**\n\nItalian espresso blends deliberately include Robusta for crema. Vietnamese coffee is often Robusta."
  },
  {
    "slug": "burundi-coffee",
    "title": "Burundi: East Africa's best kept coffee secret",
    "category": "beans",
    "excerpt": "You probably haven't had Burundian coffee. You should fix that immediately.",
    "date": "Dec 7, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
    "content": "Burundi produces some of the most complex coffees in East Africa, largely from Bourbon variety at 1500-2000m.\n\n**Tasting notes**\n\nRed fruit, peach, blackcurrant, milk chocolate. Bright acidity, medium body.\n\n**Find it at**\n\nOna, Market Lane, and other specialty roasters."
  },
  {
    "slug": "rwanda-coffee",
    "title": "Rwanda: how specialty coffee rebuilt an industry",
    "category": "beans",
    "excerpt": "After 1994, Rwanda rebuilt its coffee industry with specialty at the centre.",
    "date": "Nov 30, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    "content": "In the early 2000s, Rwanda made a deliberate shift to specialty production.\n\n**Tasting notes**\n\nBright citrus, floral, stone fruit, red berry. Clean and well-structured.\n\n**Best from**\n\nNyamasheke and Huye districts."
  },
  {
    "slug": "coffee-terroir",
    "title": "Coffee terroir: why the same variety tastes different everywhere",
    "category": "beans",
    "excerpt": "Bourbon grown in Rwanda tastes different to Bourbon grown in El Salvador. Here's why.",
    "date": "Nov 15, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80",
    "content": "**What is terroir?**\n\nBorrowed from wine \u2014 the complete natural environment: soil, climate, altitude, rainfall.\n\n**How altitude affects flavour**\n\nHigher altitude = cooler = slower maturation = denser beans = more complexity.\n\n**Soil matters**\n\nVolcanic soils contribute mineral, distinctive character."
  },
  {
    "slug": "direct-trade-vs-fair-trade",
    "title": "Direct trade vs fair trade: what the labels actually mean",
    "category": "beans",
    "excerpt": "You see these words on every specialty bag. Here's what they actually mean.",
    "date": "Nov 8, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
    "content": "**Fair Trade certification**\n\nMinimum price guarantees, cooperative requirements. The floor, not the ceiling.\n\n**Direct trade**\n\nNot a certification \u2014 a relationship. The roaster buys directly from the farmer.\n\n**Which is better?**\n\nA reputable roaster doing genuine direct trade is better than certification alone."
  },
  {
    "slug": "costa-rica-coffee",
    "title": "Costa Rica: the country that made quality a national priority",
    "category": "beans",
    "excerpt": "Costa Rica banned Robusta in 1989. Only Arabica by law. The quality shows.",
    "date": "Jan 10, 2026",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    "content": "Costa Rica banned Robusta in 1989. By law, only Arabica. That commitment shows in the cup.\n\n**Tasting notes**\n\nBright acidity, honey sweetness, clean finish. Citrus and brown sugar.\n\n**Honey processing**\n\nCosta Rica popularised honey processing \u2014 removing skin but leaving some mucilage."
  },
  {
    "slug": "guatemala-antigua",
    "title": "Guatemala Antigua: chocolate and spice from the volcanic highlands",
    "category": "beans",
    "excerpt": "The volcanic terroir of Antigua produces coffee with a flavour profile unlike anywhere else.",
    "date": "Oct 20, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
    "content": "Antigua sits at 1500m, surrounded by three volcanoes. The volcanic ash soil gives the coffee its distinctive profile.\n\n**Tasting notes**\n\nDark chocolate, brown spice, mild citrus, full body.\n\n**Roast**\n\nWorks well as medium-dark. Holds up to a longer roast better than most Central Americans."
  },
  {
    "slug": "panama-gesha-experience",
    "title": "Spending $80 on a single cup of coffee: was it worth it?",
    "category": "beans",
    "excerpt": "Hacienda La Esmeralda Gesha. The most expensive coffee in the world. Here's the experience.",
    "date": "Oct 10, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    "content": "I paid $80 for a single cup of Hacienda La Esmeralda Gesha.\n\n**The taste**\n\nJasmine, bergamot, ripe peach, honey. Extraordinarily complex. Unlike anything before or since.\n\n**Was it worth it?**\n\nAs an experience: yes. As value: no. As a coffee milestone: absolutely."
  },
  {
    "slug": "washed-vs-natural-side-by-side",
    "title": "Washed vs natural: tasting the same bean both ways",
    "category": "beans",
    "excerpt": "We got the same lot processed two different ways. The difference is staggering.",
    "date": "Sep 5, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80",
    "content": "Same farm, same harvest, processed two ways. The results were remarkable.\n\n**The washed version**\n\nClean, bright, citrus forward. You could taste the terroir clearly.\n\n**The natural version**\n\nFruity, heavier, wine-like. The processing dominated the cup.\n\n**The lesson**\n\nProcessing is not just a step \u2014 it's a flavour ingredient."
  },
  {
    "slug": "decaf-processing",
    "title": "How decaf is made: the methods that preserve flavour",
    "category": "beans",
    "excerpt": "Solvent, Swiss Water, CO2. Three approaches to removing caffeine. Only one is worth drinking.",
    "date": "Nov 1, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
    "content": "**Solvent process**\n\nChemicals strip caffeine and flavour. Most common, cheapest. The decaf you don't want.\n\n**Swiss Water Process**\n\nWater and carbon filter only. 99.9% caffeine-free, much better flavour.\n\n**CO2 Process**\n\nSupercritical CO2 selectively removes caffeine. Most expensive, most flavour-preserving.\n\n**What to look for**\n\nSwiss Water or CO2 process. Anything else is a pass."
  },
  {
    "slug": "hand-grinder-test",
    "title": "I tested 6 hand grinders so you don't have to",
    "category": "gear",
    "excerpt": "From $30 bin finds to $300 precision instruments. Here's what actually matters.",
    "date": "March 5, 2026",
    "readTime": "7 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1517145921023-bc9c4ee4d2b8?w=800&q=80",
    "content": "Three weeks, six grinders, same beans every day.\n\n**Winner: 1Zpresso JX-Pro ($180)**\n\nRivals electric grinders twice the price. The clear winner.\n\n**Best value: Timemore C2 ($80)**\n\nWill embarrass grinders twice its price. Start here.\n\n**Skip: Generic Amazon grinder ($30)**\n\nPlastic burrs, falls apart. Just don't."
  },
  {
    "slug": "best-budget-espresso-machine",
    "title": "The best espresso machines under $500 in 2026",
    "category": "gear",
    "excerpt": "You don't need $3000 for great espresso. The honest guide to machines that actually work.",
    "date": "Feb 28, 2026",
    "readTime": "6 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    "content": "**Gaggia Classic Pro ($450)**\n\nThe benchmark for budget home espresso. Commercial steam wand, 58mm portafilter, modifiable.\n\n**Breville Bambino Plus ($600)**\n\nAutomatic steam wand, fast heat-up, excellent for beginners.\n\n**What to avoid**\n\nPressurised basket machines \u2014 they lie to you about extraction quality."
  },
  {
    "slug": "scale-guide",
    "title": "Why every coffee setup needs a scale (and which one to buy)",
    "category": "gear",
    "excerpt": "The $15 upgrade that will improve your coffee more than any other purchase.",
    "date": "Feb 22, 2026",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1517145921023-bc9c4ee4d2b8?w=800&q=80",
    "content": "**Cheapest option that works**\n\nAmerican Weigh LB-3000 (~$20). Accurate to 0.1g.\n\n**Enthusiast pick**\n\nAcaia Pearl ($250). Fast response, app connectivity, timer built in.\n\n**Middle ground**\n\nHario V60 Drip Scale ($60). Timer included, looks good."
  },
  {
    "slug": "gooseneck-kettle-guide",
    "title": "Gooseneck kettles: do you actually need one?",
    "category": "gear",
    "excerpt": "For espresso, no. For filter, yes. Here's why and which ones are worth buying.",
    "date": "Feb 16, 2026",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1484980972926-edee96e0960d?w=800&q=80",
    "content": "**Why gooseneck matters for pour over**\n\nControl over flow rate is everything in a V60 or Chemex. A standard kettle pours too fast.\n\n**Temperature control is non-negotiable**\n\nGet a variable temperature model.\n\n**The picks**\n\nFellow Stagg EKG (~$220): the best. Hario Buono (~$60): the affordable starter."
  },
  {
    "slug": "aeropress-review",
    "title": "Aeropress Original: still the best $60 you'll spend on coffee",
    "category": "gear",
    "excerpt": "15 years old, still the benchmark. The complete 2026 review.",
    "date": "Feb 10, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800&q=80",
    "content": "**Why it's still the one**\n\nMakes excellent coffee. Nearly indestructible. Costs $60. These facts have not changed.\n\n**The competition**\n\nAeropress Go, Delter Press, Fellow Prismo. All fine. None replace the original.\n\n**The only downside**\n\nOne cup at a time. If you need more, buy two."
  },
  {
    "slug": "burr-grinder-guide",
    "title": "How to buy a burr grinder: the complete guide",
    "category": "gear",
    "excerpt": "Flat burrs vs conical burrs. Single dose vs hopper. The guide to not buying the wrong one.",
    "date": "Feb 4, 2026",
    "readTime": "6 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1517145921023-bc9c4ee4d2b8?w=800&q=80",
    "content": "**Flat burrs**\n\nClarity and brightness. Examples: Niche Zero, DF64.\n\n**Conical burrs**\n\nSweeter, more body. Examples: Comandante, Mazzer.\n\n**For espresso**\n\nNiche Zero, DF64, Eureka Mignon.\n\n**For filter**\n\nBaratza Encore. Comandante C40 for hand grinding."
  },
  {
    "slug": "v60-vs-chemex",
    "title": "V60 vs Chemex: which pour over brewer is right for you?",
    "category": "gear",
    "excerpt": "Both make excellent filter coffee. They taste different and suit different people.",
    "date": "Dec 29, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1522125670776-3c7abb882bc2?w=800&q=80",
    "content": "**V60**\n\nThinner filter, more body, more oils. More responsive to technique.\n\n**Chemex**\n\nThicker filter, cleaner cup, less body. Beautiful.\n\n**Which to buy first**\n\nV60. Cheaper, more versatile, quicker to learn."
  },
  {
    "slug": "niche-zero-review",
    "title": "Niche Zero grinder: two years on, still worth it?",
    "category": "gear",
    "excerpt": "The grinder that changed home espresso. Two years of daily use. The honest assessment.",
    "date": "Dec 8, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800&q=80",
    "content": "**The Niche Zero ($700)**\n\nZero-retention, conical burr, single dose. Radically simplified workflow.\n\n**Two years on**\n\nBurrs still sharp. Zero meaningful retention. Consistent daily results.\n\n**The competition**\n\nDF64 Gen 2 ($400) at a lower price. Niche is still better to live with \u2014 quieter, cleaner."
  },
  {
    "slug": "gaggia-classic-mods",
    "title": "Gaggia Classic mods: make a $1500 machine for $100",
    "category": "gear",
    "excerpt": "The Gaggia Classic Pro is the best value espresso machine. These mods make it exceptional.",
    "date": "Nov 10, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1518057111178-44a106bad636?w=800&q=80",
    "content": "**PID kit (~$50)**\n\nReplaces manual thermostat with PID controller. Accuracy to 0.5\u00b0C. Most impactful mod.\n\n**OPV adjustment (free)**\n\nReduce over-pressure valve from 12 bar to 9 bar. 5 minutes with a screwdriver.\n\n**Steam wand tip (~$5)**\n\nReplace stock tip with 4-hole tip for much better texture."
  },
  {
    "slug": "fellow-stagg-review",
    "title": "Fellow Stagg EKG review: beautiful, functional, worth the price",
    "category": "gear",
    "excerpt": "The kettle that made variable temperature mainstream.",
    "date": "Dec 1, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1484980972926-edee96e0960d?w=800&q=80",
    "content": "**What it does**\n\nPrecise temperature control (1\u00b0C increments), hold function, gooseneck precision.\n\n**Alternatives**\n\nTimemore Pulsar (~$100): similar at lower price. Hario Buono Electric ($80): simpler but effective.\n\n**Verdict**\n\nAt $220 it's the premium choice \u2014 genuinely excellent."
  },
  {
    "slug": "acaia-pearl-review",
    "title": "Acaia Pearl scale: is it really worth $250?",
    "category": "gear",
    "excerpt": "The most expensive coffee scale you can buy. Is it actually worth the price?",
    "date": "Nov 20, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1517145921023-bc9c4ee4d2b8?w=800&q=80",
    "content": "**What you get**\n\nResponse time measured in milliseconds (critical for espresso). App connectivity. Auto-tare. Built-in timer. Durable.\n\n**The honest truth**\n\nFor filter coffee, a $20 scale does 90% of what the Acaia does. For espresso, the fast response genuinely matters.\n\n**Verdict**\n\nIf you're serious about espresso: buy it. If you're mainly brewing filter: get the Hario V60 scale for $60."
  },
  {
    "slug": "home-roaster-guide",
    "title": "Home coffee roasters: from popcorn popper to Gene Cafe",
    "category": "gear",
    "excerpt": "Roasting at home means beans roasted 30 minutes ago. Here's how to start.",
    "date": "Nov 3, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800&q=80",
    "content": "**Popcorn popper ($30)**\n\nWorks. Loud. Small batches only. No temperature control.\n\n**Behmor 1600 ($350)**\n\nDrum roaster, 450g batches, smoke suppressor. Good entry-level dedicated roaster.\n\n**Gene Cafe CBR-101 ($600)**\n\nExcellent airflow, great results. The step-up choice.\n\n**Green coffee source**\n\nSweetMarias.com is the go-to for home roasters."
  },
  {
    "slug": "espresso-machine-maintenance",
    "title": "Espresso machine maintenance: the complete guide",
    "category": "gear",
    "excerpt": "Clean your machine. Descale it. Replace the gaskets. Here's when and how.",
    "date": "Jan 5, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&q=80",
    "content": "**Daily**\n\nBackflush with water. Wipe steam wand immediately. Rinse portafilter.\n\n**Weekly**\n\nBackflush with Cafiza tablet. Soak portafilter basket overnight.\n\n**Monthly**\n\nDescale if hard water. Replace shower screen gasket if worn.\n\n**Every 6 months**\n\nReplace group gasket. Check steam tip."
  },
  {
    "slug": "aeropress-accessories",
    "title": "Aeropress accessories worth buying (and the ones that aren't)",
    "category": "gear",
    "excerpt": "Metal filters, Fellow Prismo, Able Kone. What's worth your money?",
    "date": "Nov 24, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=800&q=80",
    "content": "**Able Disk Fine (~$15)**\n\nReusable metal filter. More body, less waste. Worth it.\n\n**Fellow Prismo (~$30)**\n\nPressure-actuated valve, no-drip brewing, espresso-style shots. Genuinely useful.\n\n**Barista & Co Twist Press (~$20)**\n\nSilicone seal replacement. Better seal, easier press.\n\n**Skip: Most recipe apps**\n\nJust use a timer and a scale."
  },
  {
    "slug": "barista-home-setup",
    "title": "The one thing baristas notice about your home setup",
    "category": "tips",
    "excerpt": "It's not your machine. It's not your beans. It's the one thing professionals spot immediately.",
    "date": "March 1, 2026",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800&q=80",
    "content": "I asked six working baristas what they notice first when someone invites them over for coffee. Every single one said the same thing: your grinder.\n\n**Why grinders matter more than machines**\n\nA blade grinder produces uneven particle sizes. Dust over-extracts (bitter), rocks under-extract (sour). A burr grinder changes everything.\n\n**What to buy**\n\nFor espresso: Breville Smart Grinder Pro ($300). For filter: Baratza Encore ($200). For hand grinding: Timemore C2 ($80)."
  },
  {
    "slug": "water-quality-tips",
    "title": "5 ways to improve your coffee water today",
    "category": "tips",
    "excerpt": "Chlorinated tap water actively fights your coffee. The complete water guide.",
    "date": "Feb 14, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1484980972926-edee96e0960d?w=800&q=80",
    "content": "**Tip 1: Basic Brita filter**\n\nRemoves chlorine. Cheap. Good start.\n\n**Tip 2: BWT Penguin jug**\n\nAdds magnesium back in for better extraction.\n\n**Tip 3: Third Wave Water minerals**\n\nAdd to distilled water for perfect coffee water. ~$1 per litre.\n\n**Tip 4: Never use softened water**\n\nSodium makes coffee taste flat and weird."
  },
  {
    "slug": "troubleshooting-sour-coffee",
    "title": "Why your coffee tastes sour and how to fix it",
    "category": "tips",
    "excerpt": "Sour coffee is under-extracted. The complete troubleshooting guide.",
    "date": "Nov 26, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800&q=80",
    "content": "**For espresso**\n\nGrind finer. Sour = not enough extraction = water passed too quickly.\n\n**For filter**\n\nGrind finer, use hotter water, pour more slowly.\n\n**For French press**\n\nExtend steep time or use hotter water.\n\n**Note**\n\nSour vs acidic: sour is unpleasant sharp. Bright acidity is pleasant complexity. Know the difference."
  },
  {
    "slug": "troubleshooting-bitter-coffee",
    "title": "Why your coffee tastes bitter and how to fix it",
    "category": "tips",
    "excerpt": "Bitter coffee is over-extracted. The complete guide to identifying and fixing it.",
    "date": "Nov 12, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    "content": "**For espresso**\n\nGrind coarser. Bitter = over-extraction = too much resistance.\n\n**For filter**\n\nGrind coarser or reduce water temperature.\n\n**For French press**\n\nReduce steep time. Don't leave it in the press.\n\n**Common culprits**\n\nOld beans, dirty equipment, water too hot, grind too fine."
  },
  {
    "slug": "coffee-storage-tips",
    "title": "How to store coffee beans: everything you're doing wrong",
    "category": "tips",
    "excerpt": "The fridge is wrong. The freezer might be right. The complete guide.",
    "date": "Jan 18, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80",
    "content": "**Don't use the fridge**\n\nMoisture and odour absorption. Your coffee will taste like last Tuesday's leftovers.\n\n**Do use an airtight container**\n\nWith a one-way valve. Away from light and heat. Room temperature.\n\n**The freezer (done right)**\n\nFreeze in small airtight portions. Let come to room temperature before opening. Never open a cold bag."
  },
  {
    "slug": "caffeine-content-guide",
    "title": "Caffeine content in different coffees: the actual numbers",
    "category": "tips",
    "excerpt": "Espresso has more caffeine than filter coffee. Right? Wrong.",
    "date": "Sep 30, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
    "content": "**Espresso: 60-70mg per 30ml shot**\n\nSmall and concentrated. Double shot = 120-140mg.\n\n**Filter coffee: 80-120mg per 200ml**\n\nMore total caffeine per serving because of volume.\n\n**Cold brew concentrate: 200mg+ per 200ml**\n\nThe most caffeine of any common preparation.\n\n**Light vs dark roast**\n\nLight roast has more caffeine \u2014 heat destroys it."
  },
  {
    "slug": "cleaning-coffee-equipment",
    "title": "How often to clean your coffee equipment (and how to do it)",
    "category": "tips",
    "excerpt": "Dirty equipment is the most underrated reason home coffee tastes bad.",
    "date": "Oct 28, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1518057111178-44a106bad636?w=800&q=80",
    "content": "**Grinder: monthly**\n\nRun Grindz cleaning tablets. Removes rancid old oils.\n\n**Espresso machine: daily/weekly**\n\nBackflush with water daily. Cafiza tablet weekly.\n\n**Aeropress: after every use**\n\nRinse rubber seal. Full wash weekly.\n\n**V60/Chemex: after every use**\n\nWarm water rinse is enough. Full wash weekly."
  },
  {
    "slug": "coffee-health-facts",
    "title": "The actual health effects of coffee: what the science says",
    "category": "tips",
    "excerpt": "Coffee causes cancer. Coffee prevents cancer. The truth is more nuanced than you think.",
    "date": "Oct 14, 2025",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=800&q=80",
    "content": "**The evidence is broadly positive**\n\nModerate consumption (3-5 cups/day) is associated with reduced risk of type 2 diabetes, Parkinson's, and liver disease.\n\n**The caveats**\n\nAssociation is not causation. Individual response varies significantly.\n\n**The actual risks**\n\nSleep disruption (caffeine half-life is 5-6 hours). Anxiety in sensitive individuals."
  },
  {
    "slug": "making-coffee-for-guests",
    "title": "How to make coffee for a group without losing your mind",
    "category": "tips",
    "excerpt": "Dinner party. Eight people. One espresso machine. Here's the playbook.",
    "date": "Sep 16, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&q=80",
    "content": "**Option 1: Batch brew filter**\n\nMake a large V60 (600ml-1L). Keep in thermal carafe. Serves everyone, stays hot.\n\n**Option 2: Cold brew**\n\nPrepare the night before. No stress on the night. Great for summer.\n\n**What to avoid**\n\nTrying to pull individual espresso shots for everyone. You'll miss half the dinner."
  },
  {
    "slug": "coffee-ratio-tips",
    "title": "Getting your coffee ratio right: the one number that matters",
    "category": "tips",
    "excerpt": "A scale changes everything. Here's the ratio guide for every brew method.",
    "date": "Dec 22, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800&q=80",
    "content": "**Filter: 1:15**\n\n60g coffee per litre. Start here, adjust to taste.\n\n**Espresso: 1:2**\n\n18g in, 36g out. The standard starting point.\n\n**French press: 1:12**\n\nSlightly stronger because of the immersion method.\n\n**Cold brew: 1:6**\n\nConcentrate \u2014 dilute before drinking.\n\n**The tool: a scale**\n\n$15-20. The biggest upgrade for consistency."
  },
  {
    "slug": "proud-mary-review",
    "title": "Proud Mary Melbourne: worth the hype after all these years?",
    "category": "cafes",
    "excerpt": "One of Melbourne's most famous specialty caf\u00e9s. We went back. Here's the honest 2026 verdict.",
    "date": "Feb 26, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
    "content": "Proud Mary opened in 2009 and has been consistently among Australia's best.\n\n**The coffee**\n\nStill exceptional. Single origin filter options are genuinely exciting.\n\n**The food**\n\nThe corn fritters have a cult following for good reason.\n\n**Verdict**\n\n9/10. Genuinely earned and keeps earning it."
  },
  {
    "slug": "st-ali-review",
    "title": "St Ali: still Melbourne's best or coasting on reputation?",
    "category": "cafes",
    "excerpt": "The institution that helped launch Melbourne's specialty scene. 2026 revisit.",
    "date": "Feb 15, 2026",
    "readTime": "5 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
    "content": "St Ali opened in 2005 and was genuinely transformative for Melbourne coffee.\n\n**The coffee**\n\nConsistently excellent. Seasonal single origins remain some of the most interesting in Melbourne.\n\n**The space**\n\nWarehouse conversion. Better on weekday mornings.\n\n**Verdict**\n\n8.5/10. Not coasting. Still earning it."
  },
  {
    "slug": "market-lane-review",
    "title": "Market Lane Coffee: the quiet achiever",
    "category": "cafes",
    "excerpt": "No Instagram aesthetic, no gimmicks. Just exceptional sourcing and brewing.",
    "date": "Jan 30, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
    "content": "Market Lane has multiple Melbourne locations and has been consistently excellent for over a decade.\n\n**What sets them apart**\n\nThe sourcing. Their green buyer travels to origin and the quality shows.\n\n**The brewing**\n\nEvery single origin available as filter. Baristas know the menu inside out.\n\n**Verdict**\n\n9/10. The most reliable specialty experience in Melbourne."
  },
  {
    "slug": "ona-canberra-review",
    "title": "ONA Coffee Canberra: worth the drive from Sydney?",
    "category": "cafes",
    "excerpt": "Australia's most awarded specialty roaster. We made the drive.",
    "date": "Jan 20, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
    "content": "ONA is Australia's most decorated specialty roaster. Their Canberra caf\u00e9 is the flagship experience.\n\n**The coffee**\n\nAs good as it gets in Australia. The filter menu is extraordinary.\n\n**Is it worth the drive?**\n\nFor coffee-obsessed people: absolutely yes.\n\n**Verdict**\n\n9.5/10."
  },
  {
    "slug": "seven-seeds-review",
    "title": "Seven Seeds Melbourne: the blueprint for specialty coffee",
    "category": "cafes",
    "excerpt": "The caf\u00e9 that helped set the template for what specialty coffee could be in Australia.",
    "date": "Jan 10, 2026",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
    "content": "Seven Seeds opened in Carlton in 2007 and helped establish Melbourne as a world-class coffee city.\n\n**The space**\n\nWarehouse, skylights, long communal tables. Relaxed and serious simultaneously.\n\n**The filter menu**\n\nExtensive, changed regularly.\n\n**Verdict**\n\n8.5/10. A landmark that still delivers."
  },
  {
    "slug": "mecca-coffee-sydney",
    "title": "Mecca Coffee Sydney: the city's most consistent specialty",
    "category": "cafes",
    "excerpt": "Sydney's answer to Melbourne's specialty scene. And it's a very good answer.",
    "date": "Dec 15, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
    "content": "Mecca has been at the forefront of Sydney specialty for over a decade.\n\n**The coffee**\n\nImpeccably sourced and roasted. The espresso is always on point.\n\n**The space**\n\nSurry Hills location is the best \u2014 warehouse feel, excellent light.\n\n**Verdict**\n\n8.5/10. The benchmark for Sydney specialty."
  },
  {
    "slug": "single-o-surry-hills",
    "title": "Single O Surry Hills: doing things differently",
    "category": "cafes",
    "excerpt": "The tap system, the transparency, the commitment to their own way of doing things.",
    "date": "Nov 25, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
    "content": "Single O is famous for their on-tap cold brew system and extreme sourcing transparency.\n\n**The tap system**\n\nBatch brew and cold brew on tap. Innovative and practical.\n\n**The sourcing**\n\nPublish their FOB prices online. Genuinely committed to direct relationships.\n\n**Verdict**\n\n9/10. One of the most interesting caf\u00e9s in Australia."
  },
  {
    "slug": "blue-bottle-coffee",
    "title": "Blue Bottle Coffee: still the future or showing its age?",
    "category": "cafes",
    "excerpt": "The caf\u00e9 that brought third wave coffee mainstream. Where does it stand in 2026?",
    "date": "Sep 20, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
    "content": "Blue Bottle launched in Oakland in 2002 and helped bring specialty coffee to mainstream consciousness.\n\n**The coffee in 2026**\n\nStill good. Not groundbreaking anymore \u2014 the field has caught up.\n\n**The design**\n\nStill beautiful. The minimalist aesthetic holds up.\n\n**Verdict**\n\n7.5/10. Good but no longer exceptional relative to the field."
  },
  {
    "slug": "gail-london-review",
    "title": "GAIL Bakery London: when the bread is as good as the coffee",
    "category": "cafes",
    "excerpt": "The London chain that somehow manages to do both perfectly.",
    "date": "Oct 15, 2025",
    "readTime": "4 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&q=80",
    "content": "GAIL has locations across London and manages the rare feat of being both a great bakery and great coffee shop.\n\n**The coffee**\n\nMonmouth-sourced espresso. Consistently good.\n\n**The food**\n\nThe sourdough. The pastries. The cinnamon bun. All extraordinary.\n\n**Verdict**\n\n8/10. The complete caf\u00e9 package."
  },
  {
    "slug": "sensory-lab-melbourne",
    "title": "Sensory Lab Melbourne: serious coffee, beautiful space",
    "category": "cafes",
    "excerpt": "Inside David Jones doesn't sound like a specialty destination. It absolutely is.",
    "date": "Nov 5, 2025",
    "readTime": "3 min read",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&q=80",
    "content": "Sensory Lab operates out of David Jones stores but the coffee program is exceptional.\n\n**The coffee**\n\nFrequently rotating single origins. Excellent filter menu. Well-calibrated espresso.\n\n**The accessibility**\n\nCentral CBD location makes it one of the most accessible specialty caf\u00e9s in Melbourne.\n\n**Verdict**\n\n8/10."
  }
];

window.SPILL_BEANS = [
  {
    "id": "yirgacheffe-g1",
    "name": "Yirgacheffe G1",
    "origin": "Ethiopia",
    "process": "Natural",
    "notes": "Blueberry, dark chocolate, a little bit of chaos.",
    "score": 9.1,
    "price": "~$28 / 250g",
    "bestFor": "Filter",
    "verdict": "Buy it immediately"
  },
  {
    "id": "huila-excelso",
    "name": "Huila Excelso",
    "origin": "Colombia",
    "process": "Washed",
    "notes": "Caramel, red apple, consistent as your most reliable friend.",
    "score": 8.8,
    "price": "~$24 / 250g",
    "bestFor": "Espresso & Filter",
    "verdict": "Crowd pleaser"
  },
  {
    "id": "antigua-shb",
    "name": "Antigua SHB",
    "origin": "Guatemala",
    "process": "Honey",
    "notes": "Brown sugar, stone fruit, wildly good as filter.",
    "score": 8.6,
    "price": "~$26 / 250g",
    "bestFor": "Filter",
    "verdict": "Underrated"
  },
  {
    "id": "mandheling-dp",
    "name": "Mandheling DP",
    "origin": "Sumatra",
    "process": "Wet-hulled",
    "notes": "Earthy, cedar, full body. The coffee equivalent of a firm handshake.",
    "score": 8.3,
    "price": "~$22 / 250g",
    "bestFor": "Espresso",
    "verdict": "For the bold"
  },
  {
    "id": "kenya-aa",
    "name": "Kenya AA",
    "origin": "Kenya",
    "process": "Washed",
    "notes": "Blackcurrant, grapefruit, brown sugar. High acidity, deeply complex.",
    "score": 9.0,
    "price": "~$32 / 250g",
    "bestFor": "Filter",
    "verdict": "Life-changing"
  },
  {
    "id": "bourbon-el-salvador",
    "name": "El Salvador Bourbon",
    "origin": "El Salvador",
    "process": "Washed",
    "notes": "Toffee, peach, gentle acidity. Like a warm hug in a cup.",
    "score": 8.4,
    "price": "~$25 / 250g",
    "bestFor": "Espresso & Filter",
    "verdict": "Overlooked gem"
  },
  {
    "id": "gesha-panama",
    "name": "Panama Gesha",
    "origin": "Panama",
    "process": "Washed",
    "notes": "Jasmine, bergamot, ripe peach. The most complex coffee on earth.",
    "score": 9.8,
    "price": "~$120 / 100g",
    "bestFor": "Filter",
    "verdict": "Once in a lifetime"
  },
  {
    "id": "natural-brazil",
    "name": "Brazil Fazenda Cachoeira",
    "origin": "Brazil",
    "process": "Natural",
    "notes": "Hazelnut, dark chocolate, dried fruit. The backbone of great blends.",
    "score": 8.2,
    "price": "~$20 / 250g",
    "bestFor": "Espresso",
    "verdict": "The reliable one"
  },
  {
    "id": "burundi-kayanza",
    "name": "Burundi Kayanza",
    "origin": "Burundi",
    "process": "Washed",
    "notes": "Red fruit, peach, milk chocolate. East Africa's best kept secret.",
    "score": 8.7,
    "price": "~$29 / 250g",
    "bestFor": "Filter",
    "verdict": "Seek it out"
  },
  {
    "id": "rwanda-nyamasheke",
    "name": "Rwanda Nyamasheke",
    "origin": "Rwanda",
    "process": "Washed",
    "notes": "Citrus, floral, stone fruit. A testament to what specialty coffee can do.",
    "score": 8.9,
    "price": "~$30 / 250g",
    "bestFor": "Filter",
    "verdict": "Exceptional"
  },
  {
    "id": "costa-rica-tarrazu",
    "name": "Costa Rica Tarrazu",
    "origin": "Costa Rica",
    "process": "Honey",
    "notes": "Honey sweetness, bright citrus, clean finish. Consistently excellent.",
    "score": 8.5,
    "price": "~$26 / 250g",
    "bestFor": "Espresso & Filter",
    "verdict": "Never disappoints"
  },
  {
    "id": "colombia-pink-bourbon",
    "name": "Colombia Pink Bourbon",
    "origin": "Colombia",
    "process": "Natural",
    "notes": "Strawberry, tropical fruit, rose. When you want to confuse your friends.",
    "score": 9.2,
    "price": "~$45 / 250g",
    "bestFor": "Filter",
    "verdict": "Conversation starter"
  },
  {
    "id": "ethiopia-sidama",
    "name": "Ethiopia Sidama",
    "origin": "Ethiopia",
    "process": "Natural",
    "notes": "Peach, jasmine, dark chocolate. The Yirgacheffe's equally talented sibling.",
    "score": 8.8,
    "price": "~$27 / 250g",
    "bestFor": "Filter",
    "verdict": "Don't sleep on it"
  },
  {
    "id": "yemen-mocha",
    "name": "Yemen Mocha Matari",
    "origin": "Yemen",
    "process": "Natural",
    "notes": "Wine, blueberry, spice. Ancient varietals from the birthplace of coffee.",
    "score": 8.6,
    "price": "~$55 / 250g",
    "bestFor": "Filter & Espresso",
    "verdict": "Historical experience"
  },
  {
    "id": "hawaii-kona",
    "name": "Hawaii Kona Extra Fancy",
    "origin": "Hawaii",
    "process": "Washed",
    "notes": "Milk chocolate, macadamia, gentle acidity. The most exclusive terroir.",
    "score": 8.4,
    "price": "~$80 / 250g",
    "bestFor": "Filter",
    "verdict": "Worth trying once"
  },
  {
    "id": "colombia-anaerobic",
    "name": "Colombia Anaerobic Natural",
    "origin": "Colombia",
    "process": "Anaerobic",
    "notes": "Fermented fruit, tropical, wine-like. Not for the faint-hearted.",
    "score": 8.7,
    "price": "~$38 / 250g",
    "bestFor": "Filter",
    "verdict": "Polarising but extraordinary"
  },
  {
    "id": "india-monsoon-malabar",
    "name": "India Monsoon Malabar",
    "origin": "India",
    "process": "Monsoon",
    "notes": "Earthy, spicy, low acidity, very full body. Unlike anything else.",
    "score": 7.7,
    "price": "~$22 / 250g",
    "bestFor": "Espresso",
    "verdict": "Unique experience"
  },
  {
    "id": "tanzania-peaberry",
    "name": "Tanzania Peaberry",
    "origin": "Tanzania",
    "process": "Washed",
    "notes": "Bright acidity, citrus, black tea. The Kenyan neighbour worth knowing.",
    "score": 8.3,
    "price": "~$28 / 250g",
    "bestFor": "Filter",
    "verdict": "Elegant"
  },
  {
    "id": "nicaragua-maracaturra",
    "name": "Nicaragua Maracaturra",
    "origin": "Nicaragua",
    "process": "Washed",
    "notes": "Brown sugar, apple, clean finish. Consistent and approachable.",
    "score": 8.1,
    "price": "~$23 / 250g",
    "bestFor": "Espresso & Filter",
    "verdict": "Reliable daily driver"
  },
  {
    "id": "peru-cajamarca",
    "name": "Peru Cajamarca",
    "origin": "Peru",
    "process": "Washed",
    "notes": "Chocolate, nuts, mild citrus. Underrated South American origin.",
    "score": 7.9,
    "price": "~$21 / 250g",
    "bestFor": "Espresso",
    "verdict": "Hidden value"
  },
  {
    "id": "mexico-chiapas",
    "name": "Mexico Chiapas",
    "origin": "Mexico",
    "process": "Washed",
    "notes": "Nutty, mild chocolate, low acidity. The workhorse of good blends.",
    "score": 7.8,
    "price": "~$20 / 250g",
    "bestFor": "Espresso",
    "verdict": "Solid every day"
  },
  {
    "id": "timor-leste",
    "name": "Timor-Leste Ermera",
    "origin": "Timor-Leste",
    "process": "Washed",
    "notes": "Dark chocolate, earthy, full body. Supporting an important origin.",
    "score": 7.9,
    "price": "~$22 / 250g",
    "bestFor": "Espresso",
    "verdict": "Good cause, good cup"
  },
  {
    "id": "png-highlands",
    "name": "Papua New Guinea Highlands",
    "origin": "Papua New Guinea",
    "process": "Washed",
    "notes": "Fruity, earthy, wild. Unpredictable in the best way.",
    "score": 7.8,
    "price": "~$24 / 250g",
    "bestFor": "Filter",
    "verdict": "Adventure in a bag"
  },
  {
    "id": "ecuador-washed",
    "name": "Ecuador Pichincha",
    "origin": "Ecuador",
    "process": "Washed",
    "notes": "Stone fruit, caramel, balanced. A new and exciting origin.",
    "score": 8.4,
    "price": "~$30 / 250g",
    "bestFor": "Filter",
    "verdict": "Watch this space"
  },
  {
    "id": "bolivia-caranavi",
    "name": "Bolivia Caranavi",
    "origin": "Bolivia",
    "process": "Washed",
    "notes": "Caramel, almond, soft citrus. Rare and worth seeking out.",
    "score": 8.3,
    "price": "~$34 / 250g",
    "bestFor": "Filter",
    "verdict": "Rare find"
  },
  {
    "id": "colombia-caturra-washed",
    "name": "Colombia Caturra Washed",
    "origin": "Colombia",
    "process": "Washed",
    "notes": "Red apple, caramel, clean. The textbook Colombian that never fails.",
    "score": 8.5,
    "price": "~$24 / 250g",
    "bestFor": "Espresso & Filter",
    "verdict": "The safe bet"
  },
  {
    "id": "ethiopia-guji",
    "name": "Ethiopia Guji Zone",
    "origin": "Ethiopia",
    "process": "Natural",
    "notes": "Cherry, blueberry, elderflower. Yirgacheffe's ambitious cousin.",
    "score": 9.0,
    "price": "~$31 / 250g",
    "bestFor": "Filter",
    "verdict": "Exceptional"
  },
  {
    "id": "brazil-yellow-bourbon",
    "name": "Brazil Yellow Bourbon",
    "origin": "Brazil",
    "process": "Pulped Natural",
    "notes": "Butterscotch, roasted almond, creamy. The smooth operator.",
    "score": 8.4,
    "price": "~$22 / 250g",
    "bestFor": "Espresso",
    "verdict": "Blend essential"
  },
  {
    "id": "kenya-sl28",
    "name": "Kenya SL28 Single Lot",
    "origin": "Kenya",
    "process": "Washed",
    "notes": "Blackcurrant, hibiscus, blood orange. Peak Kenyan expression.",
    "score": 9.3,
    "price": "~$42 / 250g",
    "bestFor": "Filter",
    "verdict": "The real deal"
  },
  {
    "id": "colombia-gesha",
    "name": "Colombia Gesha Washed",
    "origin": "Colombia",
    "process": "Washed",
    "notes": "Floral, bergamot, peach tea. What happens when Gesha meets Colombian terroir.",
    "score": 9.4,
    "price": "~$65 / 250g",
    "bestFor": "Filter",
    "verdict": "Worth every cent"
  }
];

window.SPILL_GEAR = [
  {
    "id": "acaia-pearl",
    "name": "Acaia Pearl Scale",
    "category": "scales",
    "icon": "\u2696\ufe0f",
    "desc": "Overkill for most people. Essential for the rest of us. Connects to an app, measures to 0.1g, charges by USB. The fastest response time of any coffee scale on the market.",
    "price": "~$250 AUD",
    "verdict": "Buy it",
    "rating": 9.5,
    "link": "https://acaia.co"
  },
  {
    "id": "aeropress",
    "name": "Aeropress Original",
    "category": "brewers",
    "icon": "\ud83e\uded9",
    "desc": "$60. Makes incredible coffee. Survives being dropped. Works anywhere. There's a reason every specialty coffee person owns one.",
    "price": "~$60 AUD",
    "verdict": "No brainer",
    "rating": 9.8,
    "link": "https://aeropress.com"
  },
  {
    "id": "1zpresso-jx",
    "name": "1Zpresso JX-Pro",
    "category": "grinders",
    "icon": "\ud83d\udd29",
    "desc": "Hand grinder that rivals electric grinders twice its price. Exceptional grind consistency for espresso and filter. Intuitive click-based adjustment.",
    "price": "~$180 AUD",
    "verdict": "Best value",
    "rating": 9.2,
    "link": "https://1zpresso.coffee"
  },
  {
    "id": "fellow-stagg",
    "name": "Fellow Stagg EKG",
    "category": "kettles",
    "icon": "\ud83c\udf21\ufe0f",
    "desc": "Temperature control to 1\u00b0C, hold function, gooseneck for precision pouring, looks incredible on your bench. Does everything you need and nothing you don't.",
    "price": "~$220 AUD",
    "verdict": "Worth it",
    "rating": 9.0,
    "link": "https://fellowproducts.com"
  },
  {
    "id": "timemore-c2",
    "name": "Timemore C2",
    "category": "grinders",
    "icon": "\u270f\ufe0f",
    "desc": "The best value hand grinder on the market. At $80 it produces results that will embarrass grinders twice its price. Start here.",
    "price": "~$80 AUD",
    "verdict": "Best entry",
    "rating": 8.8,
    "link": "https://timemore.com"
  },
  {
    "id": "v60",
    "name": "Hario V60 (size 02)",
    "category": "brewers",
    "icon": "\u2615",
    "desc": "The pour over brewer that started a movement. Ceramic or glass \u2014 both work. The conical design and spiral ribs produce a clean, bright cup.",
    "price": "~$30-60 AUD",
    "verdict": "Classic",
    "rating": 9.3,
    "link": "https://hario.com"
  },
  {
    "id": "gaggia-classic",
    "name": "Gaggia Classic Pro",
    "category": "machines",
    "icon": "\u26a1",
    "desc": "The benchmark for budget home espresso. Commercial steam wand, 58mm portafilter, modifiable with cheap upgrades. The best value espresso machine available.",
    "price": "~$450 AUD",
    "verdict": "Best budget machine",
    "rating": 9.0,
    "link": "https://gaggia.com"
  },
  {
    "id": "niche-zero",
    "name": "Niche Zero Grinder",
    "category": "grinders",
    "icon": "\ud83c\udfaf",
    "desc": "Zero-retention design, conical burr, single dose workflow. Radically simplified espresso grinding. Two years on it's still the daily driver of choice for serious home baristas.",
    "price": "~$700 AUD",
    "verdict": "The one",
    "rating": 9.4,
    "link": "https://www.nichecoffee.co.uk"
  },
  {
    "id": "chemex-6cup",
    "name": "Chemex 6-cup",
    "category": "brewers",
    "icon": "\ud83d\udd2c",
    "desc": "The most beautiful brewer in existence. Thicker filter than V60 means a cleaner cup. A design icon that also happens to make exceptional coffee.",
    "price": "~$70 AUD",
    "verdict": "Beautiful and functional",
    "rating": 9.1,
    "link": "https://chemexcoffeemaker.com"
  },
  {
    "id": "baratza-encore",
    "name": "Baratza Encore Electric Grinder",
    "category": "grinders",
    "icon": "\u2699\ufe0f",
    "desc": "The benchmark entry-level electric burr grinder for filter coffee. Consistent, reliable, serviceable. The right answer when someone asks what electric grinder to buy first.",
    "price": "~$200 AUD",
    "verdict": "Filter benchmark",
    "rating": 8.7,
    "link": "https://baratza.com"
  },
  {
    "id": "fellow-prismo",
    "name": "Fellow Prismo for Aeropress",
    "category": "accessories",
    "icon": "\ud83c\udfaa",
    "desc": "Pressure-actuated valve for the Aeropress. No-drip brewing, espresso-style concentrated shots, better travel use. A genuinely useful upgrade.",
    "price": "~$30 AUD",
    "verdict": "Worth it",
    "rating": 8.5,
    "link": "https://fellowproducts.com"
  },
  {
    "id": "airscape-canister",
    "name": "Airscape Coffee Canister",
    "category": "accessories",
    "icon": "\ud83e\uded9",
    "desc": "Vacuum lid pushes air out, one-way valve lets CO2 escape without letting oxygen in. The best mid-range coffee storage solution. Get the kilo size.",
    "price": "~$50 AUD",
    "verdict": "Buy the kilo",
    "rating": 8.9,
    "link": "https://airscapecanister.com"
  },
  {
    "id": "bwt-penguin",
    "name": "BWT Penguin Water Filter",
    "category": "accessories",
    "icon": "\ud83d\udca7",
    "desc": "Filters tap water and adds magnesium back in for better extraction. Coffee-specific filtration. Makes a genuinely noticeable difference to both flavour and espresso machine longevity.",
    "price": "~$60 AUD",
    "verdict": "Underrated upgrade",
    "rating": 8.6,
    "link": "https://bwt.com"
  },
  {
    "id": "comandante-c40",
    "name": "Comandante C40 Hand Grinder",
    "category": "grinders",
    "icon": "\ud83c\udf96\ufe0f",
    "desc": "The hand grinder that professionals actually use. German-engineered, produces exceptional grind quality for filter and espresso. The benchmark for hand grinders.",
    "price": "~$300 AUD",
    "verdict": "The professional's choice",
    "rating": 9.3,
    "link": "https://comandantegrinder.com"
  },
  {
    "id": "eureka-mignon",
    "name": "Eureka Mignon Specialita",
    "category": "grinders",
    "icon": "\ud83c\uddee\ud83c\uddf9",
    "desc": "Italian-made flat burr grinder. Whisper quiet, stepless adjustment, fast and consistent. The sweet spot between affordable and professional for home espresso.",
    "price": "~$650 AUD",
    "verdict": "The upgrade",
    "rating": 9.2,
    "link": "https://eureka.co.it"
  },
  {
    "id": "french-press-bodum",
    "name": "Bodum Chambord French Press",
    "category": "brewers",
    "icon": "\ud83e\uded6",
    "desc": "The French press that's been the benchmark since 1974. Stainless steel frame, borosilicate glass, works perfectly. No reason to buy anything else.",
    "price": "~$50 AUD",
    "verdict": "The original",
    "rating": 8.8,
    "link": "https://bodum.com"
  },
  {
    "id": "hario-drip-scale",
    "name": "Hario V60 Drip Scale",
    "category": "scales",
    "icon": "\ud83d\udcca",
    "desc": "Built-in timer, accurate to 0.1g, simple interface. The right entry-level scale for filter coffee. Does exactly what it needs to at a reasonable price.",
    "price": "~$60 AUD",
    "verdict": "Perfect entry",
    "rating": 8.5,
    "link": "https://hario.com"
  },
  {
    "id": "aeropress-go",
    "name": "Aeropress Go Travel Kit",
    "category": "brewers",
    "icon": "\u2708\ufe0f",
    "desc": "Smaller than the original, comes with a travel mug, packs into itself. Makes the same excellent coffee. The Aeropress you take everywhere.",
    "price": "~$55 AUD",
    "verdict": "Best travel brewer",
    "rating": 9.0,
    "link": "https://aeropress.com"
  },
  {
    "id": "decent-scale",
    "name": "Decent Scale",
    "category": "scales",
    "icon": "\ud83d\udcf1",
    "desc": "Made by the Decent espresso machine company. Fast response, good app, Bluetooth connectivity. The smart buy if you don't want to spend Acaia prices.",
    "price": "~$120 AUD",
    "verdict": "Smart choice",
    "rating": 8.7,
    "link": "https://decentespresso.com"
  },
  {
    "id": "peak-water-jug",
    "name": "Peak Water Jug",
    "category": "accessories",
    "icon": "\ud83c\udfd4\ufe0f",
    "desc": "Designed specifically for coffee. Adjustable mineral level, filter for chlorine. The best affordable coffee water solution. Makes a surprising difference.",
    "price": "~$70 AUD",
    "verdict": "Best value water solution",
    "rating": 8.8,
    "link": "https://peakwater.co.uk"
  },
  {
    "id": "able-disk-fine",
    "name": "Able Disk Fine (Aeropress metal filter)",
    "category": "accessories",
    "icon": "\ud83d\udcbf",
    "desc": "Reusable metal filter for the Aeropress. More body than paper, less waste. Produces a different (richer, oilier) cup than the standard paper filter. Worth having both.",
    "price": "~$15 AUD",
    "verdict": "Great add-on",
    "rating": 8.4,
    "link": "https://ablebrewing.com"
  },
  {
    "id": "pullman-tamper",
    "name": "Pullman Barista Trim Tamper",
    "category": "accessories",
    "icon": "\ud83d\udd28",
    "desc": "Self-levelling tamper that removes technique variation. Expensive for a tamper but the consistency it provides is genuinely useful, especially for beginners.",
    "price": "~$100 AUD",
    "verdict": "Worth it for beginners",
    "rating": 8.3,
    "link": "https://pullmancoffee.com"
  },
  {
    "id": "breville-bambino",
    "name": "Breville Bambino Plus",
    "category": "machines",
    "icon": "\ud83e\udd16",
    "desc": "Automatic steam wand (no technique required), 3-second heat-up, compact. The best beginner espresso machine if you don't want to learn to steam milk manually.",
    "price": "~$600 AUD",
    "verdict": "Best for beginners",
    "rating": 8.8,
    "link": "https://breville.com"
  },
  {
    "id": "third-wave-water",
    "name": "Third Wave Water Minerals",
    "category": "accessories",
    "icon": "\ud83e\uddea",
    "desc": "Sachets of minerals you add to distilled water. Produces water optimised specifically for coffee extraction. What serious home baristas use when they want complete control.",
    "price": "~$25 AUD (50 sachets)",
    "verdict": "Serious upgrade",
    "rating": 8.6,
    "link": "https://thirdwavewater.com"
  },
  {
    "id": "moka-pot-bialetti",
    "name": "Bialetti Moka Express",
    "category": "brewers",
    "icon": "\ud83c\uddee\ud83c\uddf9",
    "desc": "The original stovetop espresso maker. Been making strong, concentrated coffee since 1933. Not real espresso but genuinely delicious when used correctly. A kitchen classic.",
    "price": "~$40 AUD",
    "verdict": "A classic for good reason",
    "rating": 8.5,
    "link": "https://bialetti.com"
  },
  {
    "id": "timemore-pulsar",
    "name": "Timemore Pulsar Kettle",
    "category": "kettles",
    "icon": "\u26a1",
    "desc": "Variable temperature, gooseneck, fast heating. Offers Fellow Stagg EKG functionality at a lower price. The smart buy if you don't need the Fellow's aesthetic premium.",
    "price": "~$100 AUD",
    "verdict": "Best value kettle",
    "rating": 8.7,
    "link": "https://timemore.com"
  },
  {
    "id": "fellow-atmos",
    "name": "Fellow Atmos Coffee Canister",
    "category": "accessories",
    "icon": "\ud83c\udf00",
    "desc": "Vacuum canister with the best seal on the market. Twist the lid to create a vacuum. More effective than the Airscape for long-term storage.",
    "price": "~$60 AUD",
    "verdict": "Best storage",
    "rating": 9.0,
    "link": "https://fellowproducts.com"
  },
  {
    "id": "behmor-roaster",
    "name": "Behmor 1600 Home Roaster",
    "category": "roasters",
    "icon": "\ud83d\udd25",
    "desc": "Drum roaster, up to 450g batches, built-in smoke suppressor. The right entry-level dedicated home roaster. Opens up the world of roasting your own beans.",
    "price": "~$350 AUD",
    "verdict": "Best entry roaster",
    "rating": 8.5,
    "link": "https://behmor.com"
  },
  {
    "id": "df64-grinder",
    "name": "DF64 Gen 2 Electric Grinder",
    "category": "grinders",
    "icon": "\ud83d\udd27",
    "desc": "Flat burr grinder with near-zero retention at a fraction of the Niche Zero price. Single dose design, stepless adjustment. The value champion of electric grinders.",
    "price": "~$400 AUD",
    "verdict": "Value king",
    "rating": 9.0,
    "link": "https://df64grinder.com"
  },
  {
    "id": "cafiza-cleaner",
    "name": "Urnex Cafiza Espresso Machine Cleaner",
    "category": "accessories",
    "icon": "\ud83e\uddf9",
    "desc": "The backflush cleaning tablets used by every professional caf\u00e9 in the world. Use weekly to keep your espresso machine producing great coffee. Non-negotiable maintenance item.",
    "price": "~$20 AUD (100 tablets)",
    "verdict": "Must have",
    "rating": 9.5,
    "link": "https://urnex.com"
  }
];